---
- name: CentOS Install Nginx
  yum:
    name=nginx
    state=latest
  when:
    ansible_os_family == "RedHat"
  notify:
    - web systemd

- name: Ubuntu Install Nginx
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Ubuntu"
  notify:
    - web systemd

- name: web systemd
  systemd:
    name: nginx
    enabled: yes
    state: started
